### ISSUE TITLE
CS0246 revived

### ISSUE THREAD

**Issue by rienafairefr** [sailro/Reflexil#30]
I'm trying to modify an assembly by adding minor code to a method, and I have CS0246 The type or namespace name 'type/namespace' could not be found, all over the place. 

In a related now closed issue https://github.com/sailro/Reflexil/issues/15 it's mentioned 

"missing references, you can add them using Reflexil in the host applicaion", maybe I need new glasses but I could not find where to add the references. I see the "missing" assemblies as listed on the left side in the object browser.

Versions are reflector 8.3.0.95 and 1.9 reflexil.

Cheers,

**Comment by sailro** [comment]
![image](https://cloud.githubusercontent.com/assets/638167/8540231/e6fe9e1a-2483-11e5-8ef9-bf8b5eb34ba6.png)

![image](https://cloud.githubusercontent.com/assets/638167/8540217/b6c8817a-2483-11e5-84b7-f72b3632dae5.png)

**Comment by BlueRaja** [comment]
I see this error when a field has a type of an inner-class.  It happens with private inner-classes of the current class, and public inner-classes of other classes.

Fortunately, I was able to work around it by commenting out those fields.  If I had needed any of them though, I don't think there is a workaround.

**Comment by sailro** [comment]
Ok I see. Will investigate that.

We use a temporary assembly and we map types/fields/methods. The Type mapper is probably not smart enough to go inside nested classes.

**Comment by sailro** [comment]
Ok, now mapping issues should be fixed with https://github.com/sailro/Reflexil/commit/407dc7c9bd41a9b3286804a324618cb5434324da and
https://github.com/sailro/Reflexil/commit/01a02e2eadf2af521adb0cadc428f771c088ce33

Can you try with the latest build please and give me some feedback ?
Thanks

**Comment by BlueRaja** [comment]
I am still experiencing this issue in Reflexil 2.0.

**Comment by gholol** [comment]
@BlueRaja why did you closed this issue, It's not fixed.

@sailro I'm experiencing the same problem. 

Once I inject the inner class and then try to instantiate it in the parent:

InjectedInnerClass lko = new InjectedInnerClass();

I'm getting
CS0246 The type or namespace name 'InjectedInnerClass' could not be found ...

**Comment by sailro** [comment]
Did you try with the nightly build ? (it is not fixed in the stable releases)

**Comment by gholol** [comment]
Yes, I have the latest build (from 23 days ago). The problem still persists, injected inner classes are not detected.
